### GET adventure/cottage/boat revisions
GET http://localhost:8180/api/revision/entity
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rYWRtaW5AZ21haWwuY29tIiwiYXVkIjoid2ViIiwiaWF0IjoxNjUyNzIxNjI3LCJleHAiOjE2NTI5MDE2Mjd9.0OEC1cInOFOo-TFpmsmzls3efVNVhDMRykR6StKvjcxQwDzpBB4JuYSpaLCjxu00UFAMxjfSCp4lQNHoqStjgw

###
GET http://localhost:8180/api/revision/owners
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rYWRtaW5AZ21haWwuY29tIiwiYXVkIjoid2ViIiwiaWF0IjoxNjUyNzIxNjI3LCJleHAiOjE2NTI5MDE2Mjd9.0OEC1cInOFOo-TFpmsmzls3efVNVhDMRykR6StKvjcxQwDzpBB4JuYSpaLCjxu00UFAMxjfSCp4lQNHoqStjgw

###