### GET adventure/cottage/boat revisions
GET http://localhost:8180/api/revision/entity
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rYWRtaW5AZ21haWwuY29tIiwiYXVkIjoid2ViIiwiaWF0IjoxNjUyNzIxNjI3LCJleHAiOjE2NTI5MDE2Mjd9.0OEC1cInOFOo-TFpmsmzls3efVNVhDMRykR6StKvjcxQwDzpBB4JuYSpaLCjxu00UFAMxjfSCp4lQNHoqStjgw
###
[
  {
    "revisionType": "ENTITY",
    "entityName": "Penjanje na planinu",
    "ownerUsername": "isaprojectftn+stefanI@gmail.com",
    "idRevision": 1,
    "statusOfRevision": "PENDING",
    "clientUsername": "client TODO",
    "grade": 4,
    "comment": "Bilo je bas cool na ovoj avanturi",
    "revisionCreatedAt": "2022-05-16T19:35:30.336347",
    "adminUsername": "",
    "adminResponsDate": null
  },
  {
    "revisionType": "ENTITY",
    "entityName": "Kuca",
    "ownerUsername": "isaprojectftn+petarCO@gmail.com",
    "idRevision": 3,
    "statusOfRevision": "PENDING",
    "clientUsername": "client TODO",
    "grade": 5,
    "comment": "Kuca je bas luksuzna uzivao sam jako",
    "revisionCreatedAt": "2022-05-16T19:36:30.336347",
    "adminUsername": "",
    "adminResponsDate": null
  }
]
###
GET http://localhost:8180/api/revision/owners
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rYWRtaW5AZ21haWwuY29tIiwiYXVkIjoid2ViIiwiaWF0IjoxNjUyNzIxNjI3LCJleHAiOjE2NTI5MDE2Mjd9.0OEC1cInOFOo-TFpmsmzls3efVNVhDMRykR6StKvjcxQwDzpBB4JuYSpaLCjxu00UFAMxjfSCp4lQNHoqStjgw

###

[
  {
    "revisionType": "OWNER",
    "entityName": "",
    "ownerUsername": "isaprojectftn+stefanI@gmail.com",
    "idRevision": 2,
    "statusOfRevision": "PENDING",
    "clientUsername": "client TODO",
    "grade": 5,
    "comment": "Instruktor je prava legenda jako zanimljiv lik brutalan",
    "revisionCreatedAt": "2022-05-16T19:40:30.336347",
    "adminUsername": "",
    "adminResponsDate": null
  }
]
###
GET http://localhost:8180/api/complaint
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rYWRtaW5AZ21haWwuY29tIiwiYXVkIjoid2ViIiwiaWF0IjoxNjU0MTU4NzIyLCJleHAiOjE2NTQzMzg3MjJ9.1ytfzp4g0z6CoVtwTmIzl7bZ1iUh6VBB5d5meDxy3f4mQiKFYjrjdav0dGSz4M6qTyp-P_OR_2MgNhdA0ekxHg
###

[
  {
    "id": 1,
    "comment": "Ova avantura nije bila toliko zanimljiva",
    "nameOfService": "Penjanje na planinu",
    "userEmail": "isaprojectftn+marijaC@gmail.com",
    "createdAt": "2022-05-16T19:36:30.336347",
    "providerType": "INSTRUCTOR",
    "providerEmail": "isaprojectftn+stefanI@gmail.com",
    "revisionType": "ENTITY",
    "entityId": 1,
    "statusOfComplaint": "UNANSWERED",
    "adminEmail": null,
    "adminResponse": null,
    "adminResponsDate": null,
    "forClient": false
  },
  {
    "id": 2,
    "comment": "Instruktor mi nije dao jasne instrukcije kako da se penjem na planinu, skoro sam pao sa planine",
    "nameOfService": "",
    "userEmail": "isaprojectftn+marijaC@gmail.com",
    "createdAt": "2022-05-16T19:36:30.336347",
    "providerType": "INSTRUCTOR",
    "providerEmail": "isaprojectftn+stefanI@gmail.com",
    "revisionType": "OWNER",
    "entityId": -1,
    "statusOfComplaint": "ANSWERED",
    "adminEmail": "isaprojectftn+admin@gmail.com",
    "adminResponse": "Zao nam je zbog toga, imacemo u vidu ... :(",
    "adminResponsDate": "2022-05-16T19:36:30.336347",
    "forClient": false
  },
  {
    "id": 3,
    "comment": "Vikendica nije bila spremljena kad sam dosla, morala sam ja da cistim prvih sat vremena",
    "nameOfService": "Kuca",
    "userEmail": "isaprojectftn+marijaC@gmail.com",
    "createdAt": "2022-05-16T19:36:30.336347",
    "providerType": "COTTAGE_OWNER",
    "providerEmail": "isaprojectftn+petarCO@gmail.com",
    "revisionType": "ENTITY",
    "entityId": 2,
    "statusOfComplaint": "UNANSWERED",
    "adminEmail": null,
    "adminResponse": null,
    "adminResponsDate": null,
    "forClient": false
  },
  {
    "id": 4,
    "comment": "Vlasnik vikendice pri mom odlasku je proveravao sve zivo kao da sam lopov",
    "nameOfService": "",
    "userEmail": "isaprojectftn+marijaC@gmail.com",
    "createdAt": "2022-05-16T19:36:30.336347",
    "providerType": "COTTAGE_OWNER",
    "providerEmail": "isaprojectftn+petarCO@gmail.com",
    "revisionType": "OWNER",
    "entityId": -1,
    "statusOfComplaint": "UNANSWERED",
    "adminEmail": null,
    "adminResponse": null,
    "adminResponsDate": null,
    "forClient": false
  },
  {
    "id": 5,
    "comment": "Marija se nije lepo ponasala, vodila je u opasnost svoj i zivot ostalih ljudi",
    "nameOfService": "",
    "userEmail": "isaprojectftn+marijaC@gmail.com",
    "createdAt": "2022-06-01T19:36:30.336347",
    "providerType": "INSTRUCTOR",
    "providerEmail": "isaprojectftn+stefanI@gmail.com",
    "revisionType": "OWNER",
    "entityId": -1,
    "statusOfComplaint": "UNANSWERED",
    "adminEmail": null,
    "adminResponse": null,
    "adminResponsDate": null,
    "forClient": true
  }
]
###
GET http://localhost:8180/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rYWRtaW5AZ21haWwuY29tIiwiYXVkIjoid2ViIiwiaWF0IjoxNjUzODM2NTczLCJleHAiOjE2NTQwMTY1NzN9.rVfRY4kcZwsUFHPMqxQpbBhU3NM5PEb6Kqt9G6mn-QEChwMv0AZv-7YC1UFkbzT22gAcul9Otr6VJHl6s3EivA
###

[
  {
    "email": "isaprojectftn+stefanI@gmail.com",
    "firstName": "Stefan",
    "lastName": "Stefanovic",
    "address": {
      "country": "Slovakia",
      "city": "Bratislava",
      "street": "Miskova",
      "number": "35",
      "latitude": 14.0,
      "longitude": 24.0
    },
    "phoneNumber": "030345",
    "loyalty": {
      "score": 0,
      "loyaltyType": "REGULAR"
    },
    "userTypeISA": "INSTRUCTOR",
    "numOfPenaltyNow": 0,
    "averageGrade": 0.0,
    "biography": "moja biografija, ja sam super lik"
  },
  {
    "email": "isaprojectftn+nikolaBO@gmail.com",
    "firstName": "Nikola",
    "lastName": "Nikolic",
    "address": {
      "country": "Serbia",
      "city": "Zrenjanin",
      "street": "Zmaj Jovina",
      "number": "33",
      "latitude": 11.0,
      "longitude": 13.0
    },
    "phoneNumber": "030346",
    "loyalty": {
      "score": 0,
      "loyaltyType": "REGULAR"
    },
    "userTypeISA": "BOAT_OWNER",
    "numOfPenaltyNow": 0,
    "averageGrade": 0.0,
    "biography": ""
  },
  {
    "email": "isaprojectftn+milanCO@gmail.com",
    "firstName": "milan",
    "lastName": "milanovic",
    "address": {
      "country": "Serbia",
      "city": "Novi Sad",
      "street": "Bulevar evrope",
      "number": "10",
      "latitude": 34.0,
      "longitude": 54.0
    },
    "phoneNumber": "030345",
    "loyalty": {
      "score": 0,
      "loyaltyType": "REGULAR"
    },
    "userTypeISA": "COTTAGE_OWNER",
    "numOfPenaltyNow": 0,
    "averageGrade": 0.0,
    "biography": ""
  },
  {
    "email": "isaprojectftn+petarCO@gmail.com",
    "firstName": "petar",
    "lastName": "petrovic",
    "address": {
      "country": "Serbia",
      "city": "Beograd",
      "street": "Knez",
      "number": "35",
      "latitude": 14.0,
      "longitude": 24.0
    },
    "phoneNumber": "030345",
    "loyalty": {
      "score": 0,
      "loyaltyType": "REGULAR"
    },
    "userTypeISA": "COTTAGE_OWNER",
    "numOfPenaltyNow": 0,
    "averageGrade": 0.0,
    "biography": ""
  },
  {
    "email": "isaprojectftn+marijaC@gmail.com",
    "firstName": "Marija",
    "lastName": "Maric",
    "address": {
      "country": "Serbia",
      "city": "Novi Sad",
      "street": "Zmaj Jovina",
      "number": "33",
      "latitude": 11.0,
      "longitude": 13.0
    },
    "phoneNumber": "030348",
    "loyalty": {
      "score": 0,
      "loyaltyType": "REGULAR"
    },
    "userTypeISA": "CLIENT",
    "numOfPenaltyNow": 0,
    "averageGrade": 0.0,
    "biography": ""
  }
]
###
GET http://localhost:8180/api/instructorterms
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rc3RlZmFuSUBnbWFpbC5jb20iLCJhdWQiOiJ3ZWIiLCJpYXQiOjE2NTM4NTM0NjUsImV4cCI6MTY1NDAzMzQ2NX0.zflqTuTA2FWQXmYvdFuVWoK1yhAGPl_MBil0cMZgdmcVig_OrOjkvihEw2W_fVOtAab8JY6_wlckXbhtuQIy0w
###

[
  {
    "isa_idTerm": 1,
    "isa_termType": "TERM",
    "isa_termAvailability": "AVAILABILE",
    "isa_isTakenFastReservation": false,
    "title": "AVAILABILE",
    "start": "2022-04-05T08:00:06.235099",
    "end": "2022-07-25T08:00:06.235099"
  },
  {
    "isa_idTerm": 2,
    "isa_termType": "TERM",
    "isa_termAvailability": "UNAVAILABLE",
    "isa_isTakenFastReservation": false,
    "title": "UNAVAILABLE",
    "start": "2022-03-25T08:00:06.235099",
    "end": "2022-04-04T08:00:06.235099"
  },
  {
    "isa_idTerm": 1,
    "isa_termType": "RESERVATION",
    "isa_termAvailability": null,
    "isa_isTakenFastReservation": false,
    "title": "Penjanje na planinu",
    "start": "2022-03-10T08:00:06.235099",
    "end": "2022-03-10T12:00:06.235099"
  },
  {
    "isa_idTerm": 1,
    "isa_termType": "FAST_RESERVATION",
    "isa_termAvailability": null,
    "isa_isTakenFastReservation": false,
    "title": "Krstarenje",
    "start": "2022-07-11T14:00:06.235099",
    "end": "2022-07-11T16:00:06.235099"
  }
]
###
GET http://localhost:8180/api/instructorterms/reservation
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rc3RlZmFuSUBnbWFpbC5jb20iLCJhdWQiOiJ3ZWIiLCJpYXQiOjE2NTQwMDIzNzcsImV4cCI6MTY1NDE4MjM3N30.Qd5djUUpOu6Tvc9t7au--T-ovfq48B4SXoJM-nr8s9Xwvjol_tytX3WatAWyyTvq8cMI5sDP-41AYQpWdxT26g
###

[
  {
    "instructorUsername": "isaprojectftn+stefanI@gmail.com",
    "adventureName": "Penjanje na planinu",
    "idAdventure": 1,
    "client": {
      "id": 3,
      "email": "isaprojectftn+marijaC@gmail.com",
      "firstName": "Marija",
      "lastName": "Maric",
      "address": {
        "country": "Serbia",
        "city": "Novi Sad",
        "street": "Zmaj Jovina",
        "number": "33",
        "latitude": 11.0,
        "longitude": 13.0
      },
      "phoneNumber": "030348",
      "loyalty": {
        "score": 0,
        "loyaltyType": "REGULAR"
      }
    },
    "images": [
      {
        "id": 3,
        "name": "img3.jpg",
        "path": "images/Instructors/isaprojectftn+stefanI@gmail.com/Penjanje_na_planinu/img3.jpg"
      },
      {
        "id": 1,
        "name": "img1.jpg",
        "path": "images/Instructors/isaprojectftn+stefanI@gmail.com/Penjanje_na_planinu/img1.jpg"
      },
      {
        "id": 2,
        "name": "img2.jpg",
        "path": "images/Instructors/isaprojectftn+stefanI@gmail.com/Penjanje_na_planinu/img2.jpg"
      }
    ],
    "termType": "RESERVATION",
    "report": {
      "id": 1,
      "reservationId": 1,
      "reservationType": "INSTRUCTOR",
      "termType": "RESERVATION",
      "text": "Bilo je bas lose sa marijom nismo mogli da radimo posao kako trbea ",
      "sanctionClient": true,
      "clientShowedUp": true,
      "idClient": 3,
      "clientEmail": "isaprojectftn+marijaC@gmail.com",
      "ownerEmail": "isaprojectftn+stefanI@gmail.com",
      "createdAt": "2022-06-02T15:28:16.035316",
      "adminUsername": null,
      "sanctionApproved": false,
      "statusOfReport": "PENDING",
      "adminResponsDate": null
    },
    "additionalServices": [
      {
        "id": 3,
        "price": 7.0,
        "name": "Singing",
        "description": "Instructor will sing to you"
      },
      {
        "id": 4,
        "price": 20.0,
        "name": "Food",
        "description": "Food included"
      }
    ],
    "startTime": "2022-03-10T08:00:06.235099",
    "endTime": "2022-03-10T12:00:06.235099",
    "price": 170.0,
    "instructorComplaint": {
      "id": 5,
      "comment": "Marija se nije lepo ponasala, vodila je u opasnost svoj i zivot ostalih ljudi",
      "userEmail": "isaprojectftn+marijaC@gmail.com",
      "createdAt": "2022-06-01T19:36:30.336347",
      "providerType": "INSTRUCTOR",
      "providerEmail": "isaprojectftn+stefanI@gmail.com",
      "revisionType": "OWNER",
      "entityId": -1,
      "statusOfComplaint": "UNANSWERED",
      "adminEmail": null,
      "adminResponse": null,
      "adminResponsDate": null,
      "idReservation": 1,
      "forClient": true,
      "fastReservation": false
    },
    "statusOfReservation": "ACTIVE",
    "address": {
      "country": "Slovakia",
      "city": "Bratislava",
      "street": "Miskova",
      "number": "35",
      "latitude": 14.0,
      "longitude": 24.0
    },
    "insFastResHistories": null,
    "idReservation": 1,
    "taken": false
  },
  {
    "instructorUsername": "isaprojectftn+stefanI@gmail.com",
    "adventureName": "Krstarenje",
    "idAdventure": 2,
    "client": null,
    "images": [
      {
        "id": 5,
        "name": "img2.jpg",
        "path": "images/Instructors/isaprojectftn+stefanI@gmail.com/Krstarenje/img2.jpg"
      },
      {
        "id": 4,
        "name": "img1.jpg",
        "path": "images/Instructors/isaprojectftn+stefanI@gmail.com/Krstarenje/img1.jpg"
      }
    ],
    "termType": "FAST_RESERVATION",
    "report": null,
    "additionalServices": [
      {
        "id": 1,
        "price": 10.0,
        "name": "Wi-Fi",
        "description": "Have fun with 5G"
      }
    ],
    "startTime": "2022-07-11T14:00:06.235099",
    "endTime": "2022-07-11T16:00:06.235099",
    "price": 5.0,
    "instructorComplaint": null,
    "statusOfReservation": null,
    "address": {
      "country": "Slovakia",
      "city": "Bratislava",
      "street": "Miskova",
      "number": "35",
      "latitude": 14.0,
      "longitude": 24.0
    },
    "insFastResHistories": [
      {
        "client": {
          "id": 3,
          "email": "isaprojectftn+marijaC@gmail.com",
          "firstName": "Marija",
          "lastName": "Maric",
          "address": {
            "country": "Serbia",
            "city": "Novi Sad",
            "street": "Zmaj Jovina",
            "number": "33",
            "latitude": 11.0,
            "longitude": 13.0
          },
          "phoneNumber": "030348",
          "loyalty": {
            "score": 0,
            "loyaltyType": "REGULAR"
          }
        },
        "statusOfFastReservation": "CANCELLED"
      }
    ],
    "idReservation": 1,
    "taken": false
  }
]
###
GET http://localhost:8180/api/instructorterms/reservation/RESERVATION/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rYWxleElAZ21haWwuY29tIiwiYXVkIjoid2ViIiwiaWF0IjoxNjU0MDM1ODQwLCJleHAiOjE2NTQyMTU4NDB9.-J8wHoxJME1fiLc24XKu63POfEUp4VVhSpU43uDO3JRcQDpcwzrcyvRDpX7xaFEjy_iAbyVRy85M_cs0T6-fNA
###
GET http://localhost:8180/api/report/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rYWRtaW5AZ21haWwuY29tIiwiYXVkIjoid2ViIiwiaWF0IjoxNjU0MTgyMTYzLCJleHAiOjE2NTQzNjIxNjN9.JHjmFkogdoBCyBugAx9FhlaRPDYkgHyipSqpJFY3NzFQrWtYOsZJIxoEyH6X78nDyg8Pui3kdS-NO1Fu5r6l9A
###

[
  {
    "entityName": "Penjanje na planinu",
    "report": {
      "id": 1,
      "reservationId": 1,
      "reservationType": "INSTRUCTOR",
      "termType": "RESERVATION",
      "text": "Nisam bas zadovoljan kako se marija ponasala na rezervaciji dajte joj penal",
      "sanctionClient": true,
      "clientShowedUp": true,
      "idClient": 3,
      "clientEmail": "isaprojectftn+marijaC@gmail.com",
      "ownerEmail": "isaprojectftn+stefanI@gmail.com",
      "createdAt": "2022-06-02T16:30:04.094904",
      "adminUsername": null,
      "statusOfReport": "PENDING",
      "adminResponsDate": null,
      "adminResposne": null
    }
  }
]
###
GET http://localhost:8180/api/admin/entity
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rYWRtaW5AZ21haWwuY29tIiwiYXVkIjoid2ViIiwiaWF0IjoxNjU0MTgyMTYzLCJleHAiOjE2NTQzNjIxNjN9.JHjmFkogdoBCyBugAx9FhlaRPDYkgHyipSqpJFY3NzFQrWtYOsZJIxoEyH6X78nDyg8Pui3kdS-NO1Fu5r6l9A
###

[
  {
    "ownerType": "INSTRUCTOR",
    "ownerEmail": "isaprojectftn+stefanI@gmail.com",
    "ownerName": "Stefan Stefanovic",
    "isaEntityType": "ADVENTURE",
    "entityName": "Penjanje na planinu",
    "idEntity": 1,
    "averageGrade": 0.0,
    "price": {
      "price": 5.0,
      "priceType": "PER_HOUR"
    },
    "address": {
      "country": "Slovakia",
      "city": "Bratislava",
      "street": "Miskova",
      "number": "35",
      "latitude": 14.0,
      "longitude": 24.0
    },
    "description": "Pecacemo Ribe",
    "behaviourRules": "Nema skakanja u vodu",
    "images": [
      {
        "id": 1,
        "name": "img1.jpg",
        "path": "images/Instructors/isaprojectftn+stefanI@gmail.com/Penjanje_na_planinu/img1.jpg"
      },
      {
        "id": 2,
        "name": "img2.jpg",
        "path": "images/Instructors/isaprojectftn+stefanI@gmail.com/Penjanje_na_planinu/img2.jpg"
      },
      {
        "id": 3,
        "name": "img3.jpg",
        "path": "images/Instructors/isaprojectftn+stefanI@gmail.com/Penjanje_na_planinu/img3.jpg"
      }
    ],
    "reservationCancellationConditions": "FREE"
  },
  {
    "ownerType": "INSTRUCTOR",
    "ownerEmail": "isaprojectftn+stefanI@gmail.com",
    "ownerName": "Stefan Stefanovic",
    "isaEntityType": "ADVENTURE",
    "entityName": "Krstarenje",
    "idEntity": 2,
    "averageGrade": 0.0,
    "price": {
      "price": 5.0,
      "priceType": "PER_HOUR"
    },
    "address": {
      "country": "Slovakia",
      "city": "Bratislava",
      "street": "Miskova",
      "number": "35",
      "latitude": 14.0,
      "longitude": 24.0
    },
    "description": "Pecacemo Ribe",
    "behaviourRules": "Nema skakanja u vodu",
    "images": [
      {
        "id": 5,
        "name": "img2.jpg",
        "path": "images/Instructors/isaprojectftn+stefanI@gmail.com/Krstarenje/img2.jpg"
      },
      {
        "id": 4,
        "name": "img1.jpg",
        "path": "images/Instructors/isaprojectftn+stefanI@gmail.com/Krstarenje/img1.jpg"
      }
    ],
    "reservationCancellationConditions": "FREE"
  },
  {
    "ownerType": "INSTRUCTOR",
    "ownerEmail": "isaprojectftn+alexI@gmail.com",
    "ownerName": "Alexandar Lux",
    "isaEntityType": "ADVENTURE",
    "entityName": "Obilazak piramide",
    "idEntity": 3,
    "averageGrade": 0.0,
    "price": {
      "price": 5.0,
      "priceType": "PER_HOUR"
    },
    "address": {
      "country": "Egipt",
      "city": "Aleksandrija",
      "street": "piro",
      "number": "35",
      "latitude": 14.0,
      "longitude": 24.0
    },
    "description": "Penjamo se na piramidu, budimo faraona",
    "behaviourRules": "Nema kradje zlata, i cupova iz piramide",
    "images": [
      {
        "id": 11,
        "name": "img2.jpg",
        "path": "images/Instructors/isaprojectftn+alexI@gmail.com/Obilazak_piramide/img2.jpg"
      },
      {
        "id": 10,
        "name": "img1.jpg",
        "path": "images/Instructors/isaprojectftn+alexI@gmail.com/Obilazak_piramide/img1.jpg"
      },
      {
        "id": 12,
        "name": "img3.jpg",
        "path": "images/Instructors/isaprojectftn+alexI@gmail.com/Obilazak_piramide/img3.jpg"
      }
    ],
    "reservationCancellationConditions": "FREE"
  },
  {
    "ownerType": "BOAT_OWNER",
    "ownerEmail": "isaprojectftn+nikolaBO@gmail.com",
    "ownerName": "Nikola Nikolic",
    "isaEntityType": "BOAT",
    "entityName": "Laser 16",
    "idEntity": 1,
    "averageGrade": 0.0,
    "price": {
      "price": 10.0,
      "priceType": "PER_HOUR"
    },
    "address": {
      "country": "Serbia",
      "city": "Beograd",
      "street": "Knez Mihajlova",
      "number": "33",
      "latitude": 11.0,
      "longitude": 13.0
    },
    "description": "Najbolji brod",
    "behaviourRules": "Nema brze voznje",
    "images": [
      {
        "id": 8,
        "name": "img1.jpg",
        "path": "images/BoatOwners/isaprojectftn+nikolaBO@gmail.com/Laser_16/img1.jpg"
      }
    ],
    "reservationCancellationConditions": "FREE"
  },
  {
    "ownerType": "BOAT_OWNER",
    "ownerEmail": "isaprojectftn+nikolaBO@gmail.com",
    "ownerName": "Nikola Nikolic",
    "isaEntityType": "BOAT",
    "entityName": "Serenity",
    "idEntity": 2,
    "averageGrade": 0.0,
    "price": {
      "price": 20.0,
      "priceType": "PER_HOUR"
    },
    "address": {
      "country": "Serbia",
      "city": "Novi Sad",
      "street": "Vidovdanska",
      "number": "33",
      "latitude": 45.267136,
      "longitude": 19.83355
    },
    "description": "Oaza mira",
    "behaviourRules": "Nema brze voznje",
    "images": [
      {
        "id": 9,
        "name": "img1.jpg",
        "path": "images/BoatOwners/isaprojectftn+nikolaBO@gmail.com/Serenity/img1.jpg"
      }
    ],
    "reservationCancellationConditions": "FREE"
  },
  {
    "ownerType": "COTTAGE_OWNER",
    "ownerEmail": "isaprojectftn+milanCO@gmail.com",
    "ownerName": "milan milanovic",
    "isaEntityType": "COTTAGE",
    "entityName": "Stan",
    "idEntity": 1,
    "averageGrade": 0.0,
    "price": {
      "price": 1000.0,
      "priceType": "PER_DAY"
    },
    "address": {
      "country": "Serbia",
      "city": "Zlatibor",
      "street": "Cara Dusana",
      "number": "33",
      "latitude": 11.0,
      "longitude": 13.0
    },
    "description": "Lep stan",
    "behaviourRules": "zabranjeno glasna muzika",
    "images": [
      {
        "id": 7,
        "name": "img1.jpg",
        "path": "images/CottageOwners/isaprojectftn+milanCO@gmail.com/Stan/img1.jpg"
      }
    ],
    "reservationCancellationConditions": null
  },
  {
    "ownerType": "COTTAGE_OWNER",
    "ownerEmail": "isaprojectftn+petarCO@gmail.com",
    "ownerName": "petar petrovic",
    "isaEntityType": "COTTAGE",
    "entityName": "Kuca",
    "idEntity": 2,
    "averageGrade": 0.0,
    "price": {
      "price": 500.0,
      "priceType": "PER_DAY"
    },
    "address": {
      "country": "Serbia",
      "city": "Kopaonik",
      "street": "Cara Lazara",
      "number": "33",
      "latitude": 11.0,
      "longitude": 13.0
    },
    "description": "mala kuca",
    "behaviourRules": "hrana",
    "images": [
      {
        "id": 6,
        "name": "img1.jpg",
        "path": "images/CottageOwners/isaprojectftn+petarCO@gmail.com/Kuca/img1.jpg"
      }
    ],
    "reservationCancellationConditions": null
  }
]
###
###
GET http://localhost:8180/api/admin/test
###Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImlzYXByb2plY3RmdG4rYWRtaW5AZ21haWwuY29tIiwiYXVkIjoid2ViIiwiaWF0IjoxNjU0MTgyMTYzLCJleHAiOjE2NTQzNjIxNjN9.JHjmFkogdoBCyBugAx9FhlaRPDYkgHyipSqpJFY3NzFQrWtYOsZJIxoEyH6X78nDyg8Pui3kdS-NO1Fu5r6l9A
###